# -*- coding: utf-8 -*-
"""mm - sem - lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsL-ejwrqaGJdnHWmnplqkwAbHVF2nhG
"""

def needleman(seq1,seq2,match,mismatch,gap):
  m = len(seq2)
  n = len(seq1)

  T = [[0]*(n+1) for i in range(m+1)]
  for i in range(n+1):
    T[0][i] = i*gap
  for j in range(m+1):
    T[j][0] = j*gap

  print(T)

  for i in range(1,m+1):
    for j in range(1,n+1):
      sigma = match if seq2[i-1]==seq1[j-1] else mismatch
      T[i][j] = max(
          T[i-1][j-1] + sigma,
          T[i-1][j] + gap,
          T[i][j-1] + gap
      )
  print(T)

  i,j = m,n
  al1,al2 = "",""
  while i>0 or j>0:
    if i>0 and j>0 and T[i][j] == T[i-1][j-1] + (match if seq1[j-1]==seq2[i-1] else mismatch):
      al1,al2 = seq1[j-1]+al1,seq2[i-1]+al2
      i-=1
      j-=1
    elif i>0 and T[i][j] == T[i-1][j]+gap:
      al1,al2 = "-"+al1,seq2[i-1]+al2
      i-=1
    else:
      al1,al2 = seq1[j-1]+al1,"-"+al2
      j-=1
  print(al1)
  print(al2)

needleman("AGTCG","ATCG",1,-1,-2)

import numpy as np
import matplotlib.pyplot as plt

def generate(n,phi,theta,sigma=1,c=0):
  p = len(phi)
  q = len(theta)
  X = np.zeros(n)
  eps = np.random.normal(0,sigma,n)

  for t in range(max(p,q),n):
    ar = sum(phi[i]*X[t-i-1] for i in range(p))
    ma = sum(theta[j]*eps[t-j-1] for j in range(q))
    X[t] = c + ar +eps[t] +ma

  return X

def forecast(X,phi,theta,steps=20):
  p = len(phi)
  q = len(theta)
  n = len(X)
  eps = np.zeros(n+steps)
  forecast = np.zeros(n+steps)
  forecast[:n] = X

  for t in range(n,n+steps):
    ar = sum(phi[i]*forecast[t-i-1] for i in range(p))
    ma = sum(theta[j]*eps[t-j-1] for j in range(q))
    forecast[t] = ar + ma
  return forecast[n:]
phi = [0.6,-0.3]
theta = [0.5]

X = generate(300,phi,theta)
forecast_vals = forecast(X,phi,theta)
plt.figure(figsize=(10,6))
plt.plot(X)
plt.plot(range(len(X),len(X)+20),forecast_vals,"r--")

def arima(phi,theta,n,d,sigma=1,c=0):
  p = len(phi)
  q = len(theta)
  eps = np.random.normal(0,sigma,n)
  X = np.zeros(n)

  for t in range(max(p,q),n):
    ar = sum(phi[i]*X[t-i-1] for i in range(p))
    ma = sum(theta[j]*eps[t-j-1] for j in range(q))
    X[t] = c + ar + eps[t] + ma

  Y = X.copy()
  for _ in range(d):
    Y = np.cumsum(Y)

  return Y


phi = [0.6,-0.3]
theta = [0.5]

def differences(series,d=1):
  differ = series.copy()
  for _ in range(d):
    differ = np.diff(differ)
  return differ

def arima_forecast(series,phi,theta,d=1,steps=20):
  p = len(phi)
  q = len(theta)
  diff = differences(series)
  n = len(diff)
  eps = np.zeros(n+steps)
  forecast = np.zeros(n+steps)
  forecast[:n] = diff

  for t in range(n,n+20):
    ar = sum(phi[i]*forecast[t-i-1] for i in range(p))
    ma = sum(theta[j]*eps[t-j-1] for j in range(q))
    forecast[t] = ar + ma

  forecast_vals = forecast[n:]
  arima_forecast = forecast_vals + series[-1]
  return arima_forecast

series = arima(phi,theta,300,1)
forecast_vals = arima_forecast(series,phi,theta)

plt.plot(series)
plt.plot(range(len(series),len(series)+20),forecast_vals)

import pandas as pd
import matplotlib.pyplot as pyplot
import numpy as np

companies = ["RELIANCE","INFY","TCS","HDFCBANK"]
open_prices = pd.DataFrame()
close_prices = pd.DataFrame()

for c in companies:
  df = pd.read_csv(f"{c}.csv",parse_dates=["Date"])
  df.set_index("Date",inplace=True)
  open_prices[c] = df["Open"]
  close_prices[c] = df["Close"]

returns = (close_prices-open_prices)/open_prices
returns.dropna()

mu = returns.mean().values.reshape(-1,1)
print(mu)
cov_matrix = returns.cov().values
print(pd.DataFrame(cov_matrix).round(8))

weights = np.random.rand(500,len(companies))

weights = weights / weights.sum(axis=1)[:,None]

mu_v = weights @ mu
var_v = np.array([w @ cov_matrix @ w.T for w in weights])
sd_v = np.sqrt(var_v)

#min_variance

u = np.ones((len(companies),1))
c_inv = np.linalg.inv(cov_matrix)
w_opt = (c_inv @ u) / (u.T @ c_inv @ u)

mu_min = w_opt.T @ mu
var_min = w_opt.T @ cov_matrix @ w_opt
sd_min = np.sqrt(var_min)

print(mu_min)
print(sd_min)

plt.scatter(sd_v,mu_v,label="Random Portfolios")
plt.scatter(sd_min,mu_min,label="min portfolio")
plt.scatter(np.sqrt(np.diag(cov_matrix)),mu.flatten(),color="red",label="Individual Portfolio")
plt.legend()
plt.show()